#!/bin/bash
# Quick Test Commands for Phase 1 Optimizations

echo "🧪 Phase 1 Performance Testing"
echo "================================"
echo ""

# Check if we're on the right branch
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "performance-optimization" ]; then
    echo "⚠️  Warning: You're on branch '$CURRENT_BRANCH'"
    echo "   Switch to 'performance-optimization' branch for testing:"
    echo "   git checkout performance-optimization"
    echo ""
fi

echo "📋 Step 1: Start All Services"
echo "-----------------------------"
echo ""
echo "Open 3 separate terminal windows and run:"
echo ""
echo "Terminal 1 (BAV/SAV API):"
echo "  cd /Users/sivaramanrajagopal/Ashtavargam"
echo "  python3 -m uvicorn api_server:app --host 0.0.0.0 --port 8000"
echo ""
echo "Terminal 2 (Dasha/Gochara API):"
echo "  cd /Users/sivaramanrajagopal/Ashtavargam"
echo "  python3 -m uvicorn dasha_gochara_api:app --host 0.0.0.0 --port 8001"
echo ""
echo "Terminal 3 (Agent App):"
echo "  cd /Users/sivaramanrajagopal/Ashtavargam"
echo "  python3 -m uvicorn agent_app.main:app --host 0.0.0.0 --port 8080 --reload"
echo ""
echo "📋 Step 2: Verify Services"
echo "--------------------------"
echo ""
echo "After starting services, verify they're running:"
echo ""
echo "  curl http://localhost:8000/health"
echo "  curl http://localhost:8001/health"
echo "  curl http://localhost:8080/health"
echo ""
echo "📋 Step 3: Test in Browser"
echo "--------------------------"
echo ""
echo "1. Open: http://localhost:8080/chat"
echo "2. Enter birth details:"
echo "   - DOB: 1978-09-18"
echo "   - TOB: 17:35"
echo "   - Lat: 13.0827"
echo "   - Lon: 80.2707"
echo "   - TZ: 5.5"
echo "3. Click 'Start Chat'"
echo "4. Ask: 'What's my 7th house like?'"
echo "5. Measure response time (use browser DevTools Network tab)"
echo ""
echo "📋 Step 4: Compare Performance"
echo "------------------------------"
echo ""
echo "To compare before/after:"
echo ""
echo "Before (main branch):"
echo "  git checkout main"
echo "  # Test and note response time"
echo ""
echo "After (performance-optimization branch):"
echo "  git checkout performance-optimization"
echo "  # Test and note response time"
echo ""
echo "Expected improvement: 2-3 seconds faster"
echo ""
